import React from 'react';
import ReactMarkdown from 'react-markdown';
import { TafsirData } from '../types';
import { Icons } from './Icons';

interface TafsirModalProps {
  isOpen: boolean;
  onClose: () => void;
  data: TafsirData | null;
  isLoading: boolean;
}

export const TafsirModal: React.FC<TafsirModalProps> = ({ isOpen, onClose, data, isLoading }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-slate-900/80 backdrop-blur-sm transition-opacity" 
        onClick={onClose}
      ></div>

      {/* Modal Content */}
      <div className="relative w-full max-w-3xl max-h-[85vh] bg-white dark:bg-slate-800 rounded-2xl shadow-2xl overflow-hidden flex flex-col animate-in fade-in zoom-in-95 duration-200">
        
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/50">
          <h3 className="text-lg font-bold text-slate-800 dark:text-white flex items-center gap-2">
            <Icons.Sparkles className="w-5 h-5 text-gold-500" />
            AI Tafsir
          </h3>
          <button 
            onClick={onClose}
            className="p-2 rounded-full hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-500 dark:text-slate-400 transition-colors"
          >
            <Icons.X className="w-5 h-5" />
          </button>
        </div>

        {/* Scrollable Body */}
        <div className="overflow-y-auto flex-1 p-6 md:p-8 custom-scrollbar">
          {isLoading ? (
            <div className="flex flex-col items-center justify-center h-64 space-y-4">
              <div className="w-12 h-12 border-4 border-emerald-500 border-t-transparent rounded-full animate-spin"></div>
              <p className="text-slate-500 dark:text-slate-400 font-bengali animate-pulse">
                বিশ্লেষণ করা হচ্ছে... (Analyzing...)
              </p>
            </div>
          ) : data ? (
            <div className="space-y-6">
              {/* Reference Header */}
              <div className="bg-emerald-50 dark:bg-emerald-900/20 p-4 rounded-xl border border-emerald-100 dark:border-emerald-800/30">
                <h4 className="text-xl font-bold text-emerald-800 dark:text-emerald-300 mb-1">
                  {data.ayahReference}
                </h4>
                <p className="font-arabic text-2xl text-slate-700 dark:text-slate-300 opacity-80" dir="rtl">
                  {data.arabicSnippet}...
                </p>
              </div>

              {/* Themes */}
              <div className="flex flex-wrap gap-2">
                {data.keyThemes.map((theme, idx) => (
                  <span key={idx} className="px-3 py-1 rounded-full text-xs font-medium bg-gold-100 text-gold-700 dark:bg-gold-900/30 dark:text-gold-400 border border-gold-200 dark:border-gold-800">
                    {theme}
                  </span>
                ))}
              </div>

              {/* Main Content */}
              <div className="prose prose-slate dark:prose-invert max-w-none font-bengali prose-headings:text-emerald-700 dark:prose-headings:text-emerald-400 prose-p:leading-8">
                <ReactMarkdown>{data.tafsirText}</ReactMarkdown>
              </div>
              
              <div className="mt-8 pt-4 border-t border-slate-200 dark:border-slate-700 text-xs text-slate-400 dark:text-slate-500 italic">
                Disclaimer: This Tafsir is generated by AI based on authentic sources. Always verify with a qualified scholar for legal rulings.
              </div>
            </div>
          ) : (
             <div className="text-center text-slate-500">
                Something went wrong. Please try again.
             </div>
          )}
        </div>
      </div>
    </div>
  );
};
